```
└── 📁Delivery_pizzaria_maluca
    └── 📁packages
        └── 📁admin
            └── 📁public
                └── 📁img
                    ├── calabresa.jpg
                    ├── logo.png
                    ├── lombo.jpg
                ├── vite.svg
            └── 📁src
                └── 📁api
                    ├── auth.ts
                    ├── categories.ts
                    ├── products.ts
                    ├── upload.ts
                └── 📁components
                    └── 📁AdminLayout
                        ├── AdminLayout.ts
                └── 📁pages
                    └── 📁company
                        ├── index.ts
                    └── 📁dashboard
                        ├── index.ts
                    └── 📁login
                        ├── index.ts
                    └── 📁menu
                        └── 📁events
                            ├── categoryEvents.ts
                            ├── productEvents.ts
                            ├── productSubmit.ts
                            ├── uploadEvents.ts
                        └── 📁state
                            ├── menuState.ts
                        ├── index.ts
                        ├── renderCategories.ts
                        ├── renderCategory.ts
                        ├── renderMenu.ts
                        ├── renderProduct.ts
                        ├── renderProductModal.ts
                        ├── types.ts
                    └── 📁orders
                        ├── index.ts
                    └── 📁reports
                        ├── index.ts
                    └── 📁settings
                        ├── index.ts
                └── 📁routes
                    ├── router.ts
                └── 📁styles
                    ├── painel.css
                ├── main.ts
                ├── typescript.svg
            ├── .gitignore
            ├── index.html
            ├── package.json
            ├── tsconfig.json
            ├── vite.config.ts
        └── 📁server
            └── 📁src
                └── 📁controllers
                    ├── admin-categories.controllers.ts
                    ├── admin-products.controllers.ts
                    ├── upload.controllers.ts
                └── 📁database
                    └── 📁queries
                        ├── categories.queries.ts
                        ├── products.queries.ts
                    ├── connection.ts
                    ├── testConnection.ts
                └── 📁errors
                    ├── AppError.ts
                └── 📁middlewares
                    ├── errorHandler.ts
                    ├── upload.ts
                └── 📁routes
                    ├── admin-categories.routes.ts
                    ├── admin-products.routes.ts
                    ├── index.ts
                    ├── upload.routes.ts
                └── 📁services
                    ├── admin-categories.services.ts
                    ├── admin-products.services.ts
                └── 📁types
                    ├── menu.ts
                ├── server.ts
            └── 📁uploads
                ├── produto-1773187174463.png
                ├── produto-1773189039601.jpg
                ├── produto-1773275933379.jpg
                ├── produto-1773286958366.jpg
                ├── produto-1773335685957.jpg
                ├── produto-1773336591497.jpg
                ├── produto-1773337425306.jpg
                ├── produto-1773339553153.jpg
                ├── produto-1773345519428.jpg
                ├── produto-1773346062857.jpg
                ├── produto-1773346062860.jpg
                ├── produto-1773346993193.jpg
            ├── .env
            ├── package.json
            ├── tsconfig.json
        └── 📁shared
            └── 📁src
                ├── dom.ts
            ├── package.json
        └── 📁ui
            └── 📁public
                └── 📁fonts
                    ├── fa-brands-400.eot
                    ├── fa-brands-400.svg
                    ├── fa-brands-400.ttf
                    ├── fa-brands-400.woff
                    ├── fa-brands-400.woff2
                    ├── fa-regular-400.eot
                    ├── fa-regular-400.svg
                    ├── fa-regular-400.ttf
                    ├── fa-regular-400.woff
                    ├── fa-regular-400.woff2
                    ├── fa-solid-900.eot
                    ├── fa-solid-900.svg
                    ├── fa-solid-900.ttf
                    ├── fa-solid-900.woff
                    ├── fa-solid-900.woff2
                    ├── Poppins-Medium.otf
                    ├── Poppins-Regular.otf
            └── 📁styles
                ├── theme.css
            ├── package.json
        └── 📁web
            └── 📁public
                └── 📁fonts
                    ├── fa-brands-400.eot
                    ├── fa-brands-400.svg
                    ├── fa-brands-400.ttf
                    ├── fa-brands-400.woff
                    ├── fa-brands-400.woff2
                    ├── fa-regular-400.eot
                    ├── fa-regular-400.svg
                    ├── fa-regular-400.ttf
                    ├── fa-regular-400.woff
                    ├── fa-regular-400.woff2
                    ├── fa-solid-900.eot
                    ├── fa-solid-900.svg
                    ├── fa-solid-900.ttf
                    ├── fa-solid-900.woff
                    ├── fa-solid-900.woff2
                    ├── Poppins-Medium.otf
                    ├── Poppins-Regular.otf
                └── 📁img
                    ├── calabresa.jpg
                    ├── lombo.jpg
                ├── 2amores.jpg
                ├── 4queijos.jpg
                ├── canadense.jpg
                ├── Confete.jpg
                ├── frango.jpg
                ├── loader.png
                ├── logo.png
                ├── mussarela.jpg
                ├── palmito.jpg
                ├── romeuejulieta.jpg
                ├── Sensacao.jpg
                ├── vite.svg
            └── 📁src
                └── 📁api
                    ├── cart.ts
                    ├── menu.ts
                    ├── orders.ts
                └── 📁components
                    └── 📁BottomMenu
                        ├── BottomMenu.ts
                        ├── style.css
                    └── 📁Categories
                        ├── Categories.ts
                        ├── style.css
                    └── 📁Header
                        ├── Header.ts
                        ├── style.css
                    └── 📁MenuItemsCards
                        ├── MenuItemsCards.ts
                        ├── style.css
                    └── 📁Order
                    └── 📁TitleHeader
                        ├── style.css
                        ├── TitleHeader.ts
                └── 📁pages
                    ├── about.ts
                    ├── cart.ts
                    ├── index.ts
                    ├── item.ts
                    ├── order.ts
                └── 📁styles
                    ├── cart.css
                    ├── main.css
                    ├── order.css
                ├── main.ts
                ├── typescript.svg
            ├── .gitignore
            ├── index.html
            ├── package.json
            ├── tsconfig.json
            ├── vite.config.ts
    ├── .gitignore
    ├── api.http
    ├── package-lock.json
    ├── package.json
    └── tsconfig.base.json
```
